# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe1cfcdbe80ca8b6dc2db7da10776c45aa0b78aeefd825ee9762060134dbc16cfc0c88c3e9881242742b4d7878ce073b8953777195bc74e336692cbb3d38d135

test:
  secret_key_base: 5df05b4a99389a87a0ad1e2780fd73b0225ec0b0fef8a0cd4f00d62c82b1ade97593b89437213d1688ac7e2036dfa3e3fea1198b16e408461d2821359d4097db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  facebook_app_id: 234696070277050
  facebook_app_secret: <%= ENV["FACEBOOK_APP_SECRET"] %>
